name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '20'
  AZURE_WEBAPP_NAME: 'space-shooter-game'
  AZURE_WEBAPP_PACKAGE_PATH: './dist'

jobs:
  # Security and Code Quality Checks
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run dependency audit
      run: npm audit --audit-level=high
      continue-on-error: true

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript-typescript

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

  # Build and Test
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: security-scan
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint
      continue-on-error: true

    - name: Build application
      run: npm run build

    - name: Verify build artifacts
      run: |
        echo "Checking build output..."
        ls -la dist/
        echo "Verifying web.config exists..."
        test -f dist/web.config && echo "✓ web.config found" || echo "✗ web.config missing"
        echo "Verifying index.html exists..."
        test -f dist/index.html && echo "✓ index.html found" || echo "✗ index.html missing"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-files
        path: ./dist/
        retention-days: 5

  # Deploy to Azure Web App
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: [security-scan, build-and-test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: 
      name: Azure
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist-files
        path: ./dist/

    - name: Verify downloaded artifacts
      run: |
        echo "Downloaded artifacts:"
        ls -la dist/
        echo "Total size: $(du -sh dist/)"

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Verify deployment
      run: |
        echo "Deployment completed successfully!"
        echo "Application URL: ${{ steps.deploy-to-webapp.outputs.webapp-url }}"
        
        # Wait a moment for the app to start
        sleep 30
        
        # Check if the app is responding
        curl -f -s -o /dev/null "${{ steps.deploy-to-webapp.outputs.webapp-url }}" && \
          echo "✓ Application is responding" || \
          echo "⚠ Application may need more time to start"

    - name: Azure logout
      run: az logout
      if: always()